export const CONVERSION_LIST_REQUEST = 'CONVERSION_LIST_REQUEST';
export const CONVERSION_LIST_SUCCESS = 'CONVERSION_LIST_SUCCESS';
export const CONVERSION_LIST_FAIL = 'CONVERSION_LIST_FAIL';

export const CONVERSATION_SET_REQUEST = 'CONVERSATION_SET_REQUEST';
export const CONVERSATION_SET_SUCCESS = 'CONVERSATION_SET_SUCCESS';
export const CONVERSATION_SET_FAIL = 'CONVERSATION_SET_FAIL';
